version: "3.9"

services:
  mysql:
    container_name: my-sql
    image: mysql:latest  # You can use a different version if needed
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: kaddem/db
    ports:
      - "3306:3306"  # Map MySQL's port to the host

    volumes:
      - db:/var/lib/mysql
      - $PWD/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: kaddemProject
    image: waelabdelhedi/backendimage  # Replace with the actual image and tag
    restart: on-failure
    build: .
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/kaddem/db?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8089:8089"  # Map your application's port to the host
    depends_on:
      - mysql  # Ensure the MySQL service is started before the application
    volumes:
      - app_data:/app/data
volumes:
  app_data:  # Define the app_data volume
  db:
   driver: local